[feat] add mutex for lock key
little-cui/etcdadpt pull request #5
Opened 2021-12-13 12:43 UTC by robotLJW

2021-12-14 07:18 UTC, tianxiaoliang commented
描述使用场景和用户故事

2021-12-14 08:52 UTC, tianxiaoliang commented on mutex.go
> +func newDLock(key string, ttl int64, wait bool) (l *DLock, err error) {
l *DLock, err erro

不要声明返回变量，在return中明确

2021-12-14 09:02 UTC, tianxiaoliang commented on mutex.go
> +	success, err := Insert(m.ctx, m.key, m.id, opts...)
判断租约或者key是否存在的逻辑在哪

2021-12-14 09:13 UTC, robotLJW commented on mutex.go
> +	success, err := Insert(m.ctx, m.key, m.id, opts...)
获取锁成功，这边insert会成功，若成功会把leaseid存下来用于续约用，若失败，则看下是不是愿意等，愿意等会重试，不愿意等会报错

2021-12-14 09:18 UTC, tianxiaoliang commented on mutex.go
> +	success, err := Insert(m.ctx, m.key, m.id, opts...)
etcd的事务能力可以执行if then else逻辑，可以搜索下样例代码，如果key不存在才能够插入

2021-12-14 09:51 UTC, little-cui requested changes

2021-12-14 09:51 UTC, little-cui commented on mutex_test.go
> +	m1, err := etcdadpt.Lock("key1", 5, true)
少了TryLock场景

2021-12-14 09:55 UTC, little-cui requested changes

2021-12-14 09:55 UTC, little-cui commented on mutex.go
> +func Lock(key string, ttl int64, wait bool) (*DLock, error) {
放到API文件

2021-12-14 13:58 UTC, robotLJW commented on mutex.go
> +func Lock(key string, ttl int64, wait bool) (*DLock, error) {
已经放到api了

2021-12-14 13:58 UTC, robotLJW commented on mutex_test.go
> +	m1, err := etcdadpt.Lock("key1", 5, true)
已经添加到api了

2021-12-14 14:28 UTC, little-cui requested changes

2021-12-15 08:02 UTC, robotLJW commented on mutex.go
> +	return mutLogger
已经修改使用middleware中的log，在初始化的时候将其传入log单例

2021-12-15 09:45 UTC, little-cui requested changes

2021-12-15 09:45 UTC, little-cui commented on manager.go
> +	log.Log.Logger = cfg.Logger
log包提供SetLogger和GetLogger方法

2021-12-15 12:08 UTC, robotLJW commented on manager.go
> +	log.Log.Logger = cfg.Logger
已经添加

2021-12-16 02:15 UTC, tianxiaoliang approved these changes

2021-12-16 02:16 UTC, tianxiaoliang requested changes

2021-12-16 02:16 UTC, tianxiaoliang commented on api_test.go
> +		assert.NoError(t, err)
使用go的wrapped err特性，对具体的错误类型进行判断

2021-12-16 02:34 UTC, little-cui requested changes

2021-12-16 02:34 UTC, little-cui commented on middleware/log/logger.go
> +var log = Logger{}
不应该有默认值，已经提供默认实现在GetLogger中，用户未配置，应只有一个默认行为，不建议有2个分支

2021-12-16 02:34 UTC, little-cui commented on mutex.go
> +func (m *DLock) LeaseRenew() error {
1. 改下名字，叫Refresh吧，LeaseRenew是内部实现，不应该暴露给外部
2. 公开方法都加上注释

2021-12-16 04:08 UTC, little-cui requested changes

2021-12-16 04:08 UTC, little-cui commented on api.go
> +func Lock(key string, ttl int64, wait bool) (*DLock, error) {
没有wait参数，Lock只能是wait=true

2021-12-16 06:36 UTC, little-cui approved these changes

2021-12-16 06:39 UTC, merged